### ISSUE TITLE
AttributeError: 'numpy.ndarray' object has no attribute 'permute'

### ISSUE THREAD

**Issue by aiguo112** [gongpx20069/OpticFlow#1]
Hi there i am facing this issue, can you please tell me where am i wrong?

I have cv2 installed, python 3.6.5

![Screenshot from 2021-05-26 21-44-04](https://user-images.githubusercontent.com/81693706/119670676-ab522e80-be6b-11eb-8537-6d74ae09b21c.png)

**Comment by gongpx20069** [comment]
It seems that you should have called the wrong function “getflow_tensor”. If you want to process the array of numpy (or images from opencv), you can use the function "getflow". And if you want to process the Tensor of Pytorch, you can use the function "getflow_tensor".

**Comment by gongpx20069** [comment]
# closed
